# fly.toml app configuration file generated for fms on 2023-05-03T03:56:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fms"
primary_region = "cdg"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
