# Generated by Django 4.2 on 2023-04-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('team_building', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('analysis', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('activities_activation', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('obstacles', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('predicted_crisis', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('communication_system', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('risks_indicators', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('training_on_plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('present', models.IntegerField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_authorized_items', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('drag_running', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('drag_profits', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decentralization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_of_trustees', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('decentralization_committee', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('settlement', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('exchange', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('append', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilets_health_procedures', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('health_file', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('diagnosis_health_plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('check_health_plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('activities', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('labs_health_procedures', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_validity', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('ory_association', models.IntegerField(blank=True, null=True)),
                ('networks', models.IntegerField(blank=True, null=True)),
                ('computers', models.IntegerField(blank=True, null=True)),
                ('evaluation', models.IntegerField(blank=True, null=True)),
                ('tilo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('increase', models.IntegerField(blank=True, null=True)),
                ('decrease', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_received', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('daily_served', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('disciplined_distribution', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('health_certificate', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('not_stored_periods', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_distribution', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('supply', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('activation', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('certified', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_year_one', models.IntegerField(blank=True, null=True)),
                ('second_year_one', models.IntegerField(blank=True, null=True)),
                ('third_year_one', models.IntegerField(blank=True, null=True)),
                ('first_year_two', models.IntegerField(blank=True, null=True)),
                ('second_year_two', models.IntegerField(blank=True, null=True)),
                ('third_year_two', models.IntegerField(blank=True, null=True)),
                ('first_year_three', models.IntegerField(blank=True, null=True)),
                ('second_year_three', models.IntegerField(blank=True, null=True)),
                ('third_year_three', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_line', models.CharField(blank=True, choices=[('صالح', 1), ('غير صالح', 0)], max_length=11, null=True)),
                ('tanks', models.CharField(blank=True, choices=[('صالح', 1), ('غير صالح', 0)], max_length=11, null=True)),
                ('buckets', models.CharField(blank=True, choices=[('صالح', 1), ('غير صالح', 0)], max_length=11, null=True)),
                ('fire_extinguishers', models.CharField(blank=True, choices=[('صالح', 1), ('غير صالح', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('cabins', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('building', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('wall', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('external_factors', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('security_factors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_factors', to='EvaluateHub.securityfactors')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacles', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('plan_activation', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('team_building', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('analysis', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.material')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_training', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('training_plan', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
                ('training_plan_activation', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkersAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('present', models.IntegerField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
                ('negatives', models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkersAffairsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.workersaffairs')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersAffairsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.workersaffairs')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.training')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfers_to_school', models.IntegerField(blank=True, null=True)),
                ('transfers_from_school', models.IntegerField(blank=True, null=True)),
                ('transferred_files', models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True)),
                ('first_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_class', to='EvaluateHub.classrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAffairsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.studentsaffairs')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAffairsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.studentsaffairs')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPlanningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.strategicplanning')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPlanningIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.strategicplanning')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySafetyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.securitysafety')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySafetyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.securitysafety')),
            ],
        ),
        migrations.CreateModel(
            name='QualityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.quality')),
            ],
        ),
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.quality')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnitResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.productionunit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.productionunit')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.nutrition')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.nutrition')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoriesResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.laboratories')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoriesIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.laboratories')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=200, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school_level', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.administration')),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.cooperative')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('decentralization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.decentralization')),
                ('environment_population', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.environmentpopulation')),
                ('laboratories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.laboratories')),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.nutrition')),
                ('production_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.productionunit')),
                ('quality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.quality')),
                ('security_safety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.securitysafety')),
                ('strategic_planning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.strategicplanning')),
                ('students_affairs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.studentsaffairs')),
                ('teachers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.teachers')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.training')),
                ('workers_affairs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.workersaffairs')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentPopulationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.environmentpopulation')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentPopulationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.environmentpopulation')),
            ],
        ),
        migrations.CreateModel(
            name='DecentralizationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.decentralization')),
            ],
        ),
        migrations.CreateModel(
            name='DecentralizationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.decentralization')),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='EvaluateHub.administration')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='EvaluateHub.administration')),
            ],
        ),
    ]
