# Generated by Django 4.2 on 2023-04-14 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EvaluateHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='decentralization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decentralization', to='EvaluateHub.decentralization'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='environment_population',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environment_population', to='EvaluateHub.environmentpopulation'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='laboratories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='EvaluateHub.laboratories'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='EvaluateHub.nutrition'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='production_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_unit', to='EvaluateHub.productionunit'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='quality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='EvaluateHub.quality'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='security_safety',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_safety', to='EvaluateHub.securitysafety'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='strategic_planning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_planning', to='EvaluateHub.strategicplanning'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='student_affairs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_affairs', to='EvaluateHub.studentsaffairs'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='teachers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='EvaluateHub.teachers'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='training',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='EvaluateHub.training'),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='workers_affairs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workers_affairs', to='EvaluateHub.workersaffairs'),
        ),
    ]
