# Generated by Django 4.2 on 2023-04-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('present', models.IntegerField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentsaffairs',
            name='name',
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='transferred_files',
            field=models.CharField(blank=True, choices=[('منضبطة', '1'), ('غير منضبطة', '2')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='transfers_from_school',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='transfers_to_school',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='first_class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_class', to='EvaluateHub.classrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='second_class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_class', to='EvaluateHub.classrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsaffairs',
            name='third_class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='third_class', to='EvaluateHub.classrecord'),
            preserve_default=False,
        ),
    ]
