# Generated by Django 4.2 on 2023-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0003_classrecord_remove_studentsaffairs_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsaffairs',
            name='transferred_files',
            field=models.CharField(blank=True, choices=[('منضبطة', 1), ('غير منضبطة', 2)], max_length=11, null=True),
        ),
    ]
