# Generated by Django 4.2 on 2023-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0004_alter_studentsaffairs_transferred_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersaffairs',
            name='absent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workersaffairs',
            name='present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workersaffairs',
            name='registered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsaffairs',
            name='transferred_files',
            field=models.CharField(blank=True, choices=[('منضبط', 1), ('غير منضبط', 0)], max_length=11, null=True),
        ),
    ]
