# Generated by Django 4.2 on 2023-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0005_workersaffairs_absent_workersaffairs_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersaffairs',
            name='negatives',
            field=models.CharField(blank=True, choices=[('يوجد', 1), ('لا يوجد', 0)], max_length=11, null=True),
        ),
    ]
