# Generated by Django 4.2 on 2023-04-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0007_material_securityfactors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='decentralization',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='environment_population',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='laboratories',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='production_unit',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='strategic_planning',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='training',
        ),
    ]
