# Generated by Django 4.2 on 2023-04-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0008_remove_evaluationform_administration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='security_safety',
        ),
    ]
