# Generated by Django 4.2 on 2023-04-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0009_remove_evaluationform_security_safety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsaffairs',
            name='second_class',
        ),
        migrations.RemoveField(
            model_name='studentsaffairs',
            name='third_class',
        ),
    ]
