# Generated by Django 4.2 on 2023-04-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0010_remove_studentsaffairs_second_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='student_affairs',
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='workers_affairs',
        ),
    ]
