# Generated by Django 4.2 on 2023-04-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0011_remove_evaluationform_student_affairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='workers_affairs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers_affairs', to='EvaluateHub.workersaffairs'),
            preserve_default=False,
        ),
    ]
