# Generated by Django 4.2 on 2023-04-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0012_evaluationform_workers_affairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='student_affairs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_affairs', to='EvaluateHub.studentsaffairs'),
            preserve_default=False,
        ),
    ]
