# Generated by Django 4.2 on 2023-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0013_evaluationform_student_affairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='workers_affairs',
        ),
    ]
