# Generated by Django 4.2 on 2023-04-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0014_remove_evaluationform_workers_affairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationform',
            name='student_affairs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.studentsaffairs'),
        ),
    ]
