# Generated by Django 4.2 on 2023-04-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0016_rename_student_affairs_evaluationform_students_affairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='administration',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.administration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='cooperative',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.cooperative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='decentralization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.decentralization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='environment_population',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.environmentpopulation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='laboratories',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.laboratories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='nutrition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.nutrition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='production_unit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.productionunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='quality',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.quality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='strategic_planning',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.strategicplanning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='training',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.training'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='workers_affairs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.workersaffairs'),
            preserve_default=False,
        ),
    ]
