# Generated by Django 4.2 on 2023-04-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluateHub', '0017_evaluationform_administration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='material_five',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='material_four',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='material_six',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='material_three',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='material_two',
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='security_safety',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.securitysafety'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='teachers',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.teachers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='material_one',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EvaluateHub.material'),
        ),
    ]
